trigger:
- master

stages:
- stage: Build
  displayName: 'Build'
  jobs:
  - job: createStorageAccount
    displayName: 'Create storage account for terraform state file'
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: AzureCLI@2
      displayName: 'Create storage account for terraform state file'
      inputs:
        azureSubscription: $(azuresubscription)
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          #! /bin/bash
          az group create --location uksouth --name $(terraformstoragerg)
