name: Azure Pipelines
stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: Hosted Ubuntu 1604
    steps:
    - task: CmdLine@2
      displayName: Install Newman runner
      inputs:
        script: 'sudo npm install -g newman'  
    - task: CmdLine@2
      displayName: Run Starter API
      continueOnError: true
      inputs:
        script: 'newman run StarterAPIs.json'
        workingDirectory: 'src/automatedtesting/postman'
    
    